paritytech/scale-ts

array.ts
`array(str)` incorrectly produced a signature of `Codec<string>[]` –– this PR fixes that faulty signature
=> fix: array codec factory typing

Readme.md, _tasks/build_npm_pkg.ts, words.txt
- The repo itself has been renamed to `parity-scale-codec-ts`
- The package will be published to NPM and Denoland/x under the name `parity-scale-codec`
=> chore: package renames

compact/codec.ts, option/codec.ts, str/codec.ts, union/codec.ts
Somewhat addresses #2  
- invalid option variant indication
- attempting to decode string larger than remaining input bytes
- add error messaging regarding not finding a member codec matching a decoded discriminant
=> chore: add error case messages mentioned by @tomaka

Readme.md, mod.ts, union/key/codec.ts, union/key/test.ts, words.txt
This PR implements a codec which can encode from / decode to a TS enum of any kind.
```ts
enum Dinosaur {
Liopleurodon = "Liopleurodon",
Kosmoceratops = "Kosmoceratops",
Psittacosaurus = "Psittacosaurus",
}
const codec = s.keyLiteralUnion(
Dinosaur.Liopleurodon,
Dinosaur.Kosmoceratops,
Dinosaur.Psittacosaurus,
);
const encoded = codec.encode(Dinosaur.Psittacosaurus);
assertEquals(encoded, new Uint8Array([2]));
const decoded = codec.decode(encoded);
assertEquals(decoded, Dinosaur.Psittacosaurus);
```
=> feat: key literal unions / native TS enums

instance/codec.ts, instance/test.ts
In addition to requiring that the entries align with properties of the class (which it did before), this additionally requires that the entries align with the types of the constructor parameters.
=> Improve type safety of instance

.github/workflows/bench.yml, array/bench.ts, bool/bench.ts, compact/bench.ts, deno.jsonc, dummy/bench.ts, int/bench.ts, option/bench.ts, record/bench.ts, str/bench.ts, test-util.ts, tuple/bench.ts
This adds a bunch of benchmarks, and covers most codecs. There are a few codecs remaining without benchmarks (I think just result and union), but those can be added later.
Running `deno task bench` will run the full benchmark (around one minute on my machine), and `deno task bench [codec]` will run benchmarks just for that codec.
This also adds a workflow to automatically run benchmarks on CI, and the results are viewable in the output. I was originally going to have a comment be added to the commit with the benchmark results (like [this](https://github.com/paritytech/parity-scale-codec-ts/commit/15e9577eb3691a834e8bd5b867a36da5050de4f5#commitcomment-73445288), though the formatting is messed up), but the comment would give a notification for each commit, which I thought was too annoying.
=> Add some benchmarks

array/codec.ts
- For decode, because we know the size ahead of time, use `Array(len)` to avoid reallocation on `push`
- Inline `SizedArray` methods into `Array` to avoid class construction
(this PR is drafted because it is based off of #35)
=> Improve performance of array

constantPattern/__snapshots__/test.ts.snap, constantPattern/codec.ts, constantPattern/test.ts, mod.ts, test-util.ts
Useful for things like the [magic number in FRAME Metadata](https://docs.substrate.io/v3/runtime/metadata/#encoded-metadata-format)
=> Add `$.constantPattern`

__snapshots__/common.test.ts.snap, array/codec.ts, bool/codec.ts, common.test.ts, common.ts, compact/codec.ts, constantPattern/codec.ts, deferred/codec.ts, dummy/codec.ts, instance/codec.ts, int/codec.ts, iterable/codec.ts, never/codec.ts, object/codec.ts, option/codec.ts, option/optionBool/codec.ts, result/codec.ts, spread/codec.ts, str/codec.ts, transform/codec.ts, tuple/codec.ts, union/codec.ts, union/key/codec.ts, union/tagged/codec.ts
Fixes #61 
- Adds an `_metadata` field to `Codec`, which, if present, is `[factory, ...args]`
- Adds an `_metadata` field to `createCodec`'s argument, which, unlike that of `Codec<T>`, much be explicitly specified to be `null` if absent
- Adds a utility builder-pattern class `CodecVisitor` for traversing the metadata type-safely
=> Add metadata and visitors

.vscode/settings.json
This makes it work even if one has a user override for typescript formatter.
Not strictly necessary, but will make my life a lot easier.
=> chore: explicitly specify `dprint` as formatter for typescript in `.vscode/settings.json`

_tasks/build_npm_pkg.ts, constantPattern/codec.ts
Solves issues for dependents who can't properly shake downstream usage of `fs` and other such env-specific mods.
=> chore: get rid of non-test usage of `Deno` global

.github/dependabot.yml, .github/workflows/bench.yml, .github/workflows/release.yml, .github/workflows/test.yml
In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Additionally added `dependabot` to track GHA version changes.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/114
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies
=> ci: in gha versions add dependabot

Readme.md, array/bench.ts, array/codec.ts, bitSequence/codec.ts, compact/__snapshots__/test.ts.snap, compact/bench.ts, compact/codec.ts, compact/fixtures.rs, compact/test.ts, iterable/codec.ts, promise/__snapshots__/test.ts.snap, promise/test.ts, str/codec.ts
Currently, we treat `compact` as a single type. However, in the rust implementation, `Compact` is a generic wrapper type, and types such as `Compact<u8>`, `Compact<u128>`, etc. all have their own codec implementations. Furthermore, `Compact<>` isn't used solely for numbers – I believe libraries can implement `Encode`/`Decode` for `Compact<TheirCustomType>`.
Thus, in this library, we should reflect that, by replacing `$.compact` with `$.compactU8`, `$.compactU128`, etc.
Because the encoding of compact is the same across all `u*` types, we only need distinct implementations for the `number`-sized `u*`s and the `bigint`-sized `u*`s. Thus, we define `compactNumber` and `compactBigInt`, and simply set `$.compactU8 = compactNumber`, `$.compactU128 = compactBigInt`, etc.
We expose `$.compactU*` …
=> feat: expand compact

Readme.md, array/__snapshots__/test.ts.snap, array/codec.ts, array/test.ts
This aligns the casing with the type, `Uint8Array`. The old casing is exported as an alias for backwards compat.
=> fix: casing of `$.uint8Array` and `$.sizedUint8Array`

compact/codec.ts
The unsigned shift is cleaner than the intersection
=> chore: use an unsigned shift in `compactU32`

common.ts, iterable/codec.ts, union/codec.ts
This also fixes the metadata of `$.taggedUnion`, `$.set`, and `$.map`
=> feat: add `withMetadata`

Readme.md, codecs/promise.ts, common/codec.ts
This wasn't used anywhere other than `$.promise`. Asynchronous encoding is still supported using `.writeAsync`.
=> chore: remove `createAsyncCodec`

codecs/fixtures/union.rs, codecs/test/__snapshots__/union.test.ts.snap, codecs/test/union.test.ts, codecs/union.ts, examples/unions.eg.ts
Isn't used at all outside of `$.taggedUnion`.
Drafted until #109 is merged.
=> chore: remove `$.union`

common/codec.ts, examples/assertions.eg.ts
```ts
// using `$.assert` (no explicit typing required)
const a: unknown = 1
$.assert($.u8, a)
a // `number`
// using `Codec.assert` (explicit typing required)
const b: unknown = 2
const u8: $.Codec<number> = $.u8
u8.assert(b)
b // `number`
```
=> feat: add assert method to codec

.github/workflows/release.yml
GitHub is going to deprecate `save-state` and `set-output` commands. [More info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR adjusts GHA workflow to use new syntax.
Part of https://github.com/paritytech/ci_cd/issues/805
=> fix gha set-output command
